development:
  adapter: postgresql
  encoding: unicode
  database: angular_development
  pool: 5
  username: dbuser
  password: xyz321

production:
  adapter: postgresql
  encoding: unicode
  database: angular_development
  pool: 5
  username: dbuser
  password: xyz321