development:
  adapter: postgresql
  encoding: unicode
  database: angular_development
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: angular_development
  pool: 5
  username: postgres
  password: root